name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - 'LICENSE'
      - 'README.md'
      - '.editorconfig'
      - '.gitignore'

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  CLOUDSQL_INSTANCE: ${{ secrets.CLOUDSQL_INSTANCE }}
  CLOUDSQL_INSTANCE_CONNECTION_NAME: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:${{ secrets.CLOUDSQL_INSTANCE_NAME }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_DSN: mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@tcp(127.0.0.1:${{ secrets.MYSQL_PORT }})/${{ secrets.MYSQL_DATABASE }}
  TRADER_IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT }}/trader:${{ github.sha }}
  DASHBOARD_IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT }}/dashboard:${{ github.sha }}

jobs:
  migrate-db:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: db
    env:
      KEY_FILE: sa_key

    steps:
      - uses: actions/checkout@v1

      - name: Create Key File
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > env.KEY_FILE

      - name: Start Cloud SQL Proxy
        run: |
          docker run -d \
            -v $PWD/env.KEY_FILE:/config \
            -p 127.0.0.1:3306:3306 \
            gcr.io/cloudsql-docker/gce-proxy:1.19.1 /cloud_sql_proxy \
            -instances=$CLOUDSQL_INSTANCE_CONNECTION_NAME=tcp:0.0.0.0:3306 \
            -credential_file=/config

      - name: Install migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      - name: Migrate DB (up)
        run: |
          docker ps
          migrate -path "./migrations/" -database "$MYSQL_DSN" up

  deploy-trader:
    runs-on: ubuntu-18.04
    needs: migrate-db
    defaults:
      run:
        working-directory: trader

    steps:
      - uses: actions/checkout@v1

      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -f Dockerfile --target release -t $TRADER_IMAGE .

      - name: Push the docker image
        run: docker push $TRADER_IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy trader \
            --image $TRADER_IMAGE \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --add-cloudsql-instances $CLOUDSQL_INSTANCE_CONNECTION_NAME \
            --update-env-vars MYSQL_USER="$MYSQL_USER" \
            --update-env-vars MYSQL_PASSWORD="$MYSQL_PASSWORD" \
            --update-env-vars MYSQL_HOST="$MYSQL_HOST" \
            --update-env-vars MYSQL_PORT="$MYSQL_PORT" \
            --update-env-vars MYSQL_DATABASE="$MYSQL_DATABASE" \
            --quiet

  deploy-dashboard:
    runs-on: ubuntu-18.04
    needs: migrate-db
    defaults:
      run:
        working-directory: dashboard

    steps:
      - uses: actions/checkout@v1

      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -f Dockerfile --target release -t $TRADER_IMAGE .

      - name: Push the docker image
        run: docker push $DASHBOARD_IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dashboard \
            --image $DASHBOARD_IMAGE \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --add-cloudsql-instances $CLOUDSQL_INSTANCE_CONNECTION_NAME \
            --update-env-vars MYSQL_USER="$MYSQL_USER" \
            --update-env-vars MYSQL_PASSWORD="$MYSQL_PASSWORD" \
            --update-env-vars MYSQL_HOST="$MYSQL_HOST" \
            --update-env-vars MYSQL_PORT="$MYSQL_PORT" \
            --update-env-vars MYSQL_DATABASE="$MYSQL_DATABASE" \
            --allow-unauthenticated \
            --quiet
