name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - 'scheduler/**'
      - 'LICENSE'
      - 'README.md'
      - '.editorconfig'
      - '.gitignore'

env:
  PROXY_IMAGE: gcr.io/cloudsql-docker/gce-proxy:latest
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  CLOUDSQL_INSTANCE: ${{ secrets.CLOUDSQL_INSTANCE }}
  CLOUDSQL_INSTANCE_CONNECTION_NAME: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:${{ secrets.CLOUDSQL_INSTANCE }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_DSN: mysql://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@tcp(127.0.0.1:3306)/${{ secrets.MYSQL_DATABASE }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  BITFLYER_API_KEY: ${{ secrets.BITFLYER_API_KEY }}
  BITFLYER_API_SECRET: ${{ secrets.BITFLYER_API_SECRET }}
  PRODUCT_CODE: ${{ secrets.PRODUCT_CODE }}
  TRADER_IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT }}/trader:${{ github.sha }}
  DASHBOARD_IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT }}/dashboard:${{ github.sha }}

jobs:
  migrate-db:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: db

    steps:
      - uses: actions/checkout@v1

      - name: Start Cloud SQL Proxy
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > sa_key
          docker pull $PROXY_IMAGE
          docker run -d \
            -v $PWD/sa_key:/config \
            -p 127.0.0.1:3306:3306 \
            $PROXY_IMAGE /cloud_sql_proxy \
            -instances=$CLOUDSQL_INSTANCE_CONNECTION_NAME=tcp:0.0.0.0:3306 \
            -credential_file=/config

      - name: Install migrate
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      - name: Migrate DB (up)
        run: |
          migrate -path "./migrations/" -database "$MYSQL_DSN" up

  deploy-trader:
    runs-on: ubuntu-18.04
    needs: migrate-db
    defaults:
      run:
        working-directory: trader

    steps:
      - uses: actions/checkout@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -f Dockerfile --target release -t $TRADER_IMAGE .

      - name: Push the docker image
        run: docker push $TRADER_IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy trader \
            --image $TRADER_IMAGE \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --add-cloudsql-instances $CLOUDSQL_INSTANCE_CONNECTION_NAME \
            --update-env-vars MYSQL_USER="$MYSQL_USER" \
            --update-env-vars MYSQL_PASSWORD="$MYSQL_PASSWORD" \
            --update-env-vars MYSQL_DATABASE="$MYSQL_DATABASE" \
            --update-env-vars MYSQL_CONNECTION_NAME="$CLOUDSQL_INSTANCE_CONNECTION_NAME" \
            --update-env-vars BITFLYER_API_KEY="$BITFLYER_API_KEY" \
            --update-env-vars BITFLYER_API_SECRET="$BITFLYER_API_SECRET" \
            --update-env-vars PRODUCT_CODE="$PRODUCT_CODE" \
            --quiet

  deploy-dashboard:
    runs-on: ubuntu-18.04
    needs: migrate-db
    defaults:
      run:
        working-directory: dashboard

    steps:
      - uses: actions/checkout@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -f Dockerfile --target release -t $DASHBOARD_IMAGE .

      - name: Push the docker image
        run: docker push $DASHBOARD_IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dashboard \
            --image $DASHBOARD_IMAGE \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --add-cloudsql-instances $CLOUDSQL_INSTANCE_CONNECTION_NAME \
            --update-env-vars MYSQL_USER="$MYSQL_USER" \
            --update-env-vars MYSQL_PASSWORD="$MYSQL_PASSWORD" \
            --update-env-vars MYSQL_DATABASE="$MYSQL_DATABASE" \
            --update-env-vars MYSQL_CONNECTION_NAME="$CLOUDSQL_INSTANCE_CONNECTION_NAME" \
            --update-env-vars BITFLYER_API_KEY="$BITFLYER_API_KEY" \
            --update-env-vars BITFLYER_API_SECRET="$BITFLYER_API_SECRET" \
            --update-env-vars PRODUCT_CODE="$PRODUCT_CODE" \
            --allow-unauthenticated \
            --quiet

  deploy-functions:
    runs-on: ubuntu-18.04
    needs: migrate-db
    defaults:
      run:
        working-directory: cloud-functions

    steps:
      - uses: actions/checkout@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy export-database-to-storage \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --entry-point ExportDatabaseToStorage \
            --runtime go113 \
            --update-env-vars GCP_PROJECT="$GCP_PROJECT" \
            --update-env-vars CLOUDSQL_INSTANCE="$CLOUDSQL_INSTANCE" \
            --update-env-vars DATABASE="$MYSQL_DATABASE" \
            --update-env-vars GCS_BUCKET="$GCS_BUCKET" \
            --max-instances 1 \
            --trigger-http
